{ pkgs, ... }:

{
  fonts.fonts = with pkgs; [
    aileron
    andagii
    aurulent-sans
    baekmuk-ttf
    cabin
    caladea
    camingo-code
    cantarell-fonts
    carlito
    clearlyU
    comfortaa
    comic-neue
    comic-relief
    corefonts
    crimson
    culmus
    dosis
    eb-garamond
    emacs-all-the-icons-fonts
    emojione
    encode-sans
    envypn-font
    eunomia
    f5_6
    fantasque-sans-mono
    ferrum
    fira
    fira-code
    fira-mono
    fixedsys-excelsior
    fontconfig-penultimate
    gentium
    gentium-book-basic
    go-font
    gohufont
    google-fonts
    hanazono
    hasklig
    helvetica-neue-lt-std
    ia-writer-duospace
    ibm-plex
    inconsolata
    inriafonts
    inter-ui
    iosevka
    ipaexfont
    ipafont
    iwona
    junicode
    kochi-substitute
    kochi-substitute-naga10
    lato
    league-of-moveable-type
    liberastika
    liberationsansnarrow
    libertine
    libertinus
    libre-baskerville
    libre-bodoni
    libre-caslon
    libre-franklin
    lmodern
    lobster-two
    marathi-cursive
    material-icons
    medio
    meslo-lg
    migmix
    migu
    monoid
    mononoki
    montserrat
    mplus-outline-fonts
    mro-unicode
    myrica
    nafees
    nerdfonts
    noto-fonts
    oldsindhi
    oldstandard
    open-dyslexic
    opensans-ttf
    orbitron
    overpass
    oxygenfonts
    pecita
    penna
    poly
    powerline-fonts
    profont
    proggyfonts
    quattrocento
    quattrocento-sans
    raleway
    ricty
    rictydiminished-with-firacode
    roboto
    roboto-mono
    roboto-slab
    rounded-mgenplus
    route159
    sampradaya
    sarasa-gothic
    scheherazade
    seshat
    shrikhand
    signwriting
    siji
    source-code-pro
    source-han-code-jp
    source-sans-pro
    source-serif-pro
    stix-otf
    stix-two
    tenderness
    theano
    tipa
    tlwg
    ttf-envy-code-r
    twemoji-color-font
    ucs-fonts
    unifont
    unifont_upper
    uni-vga
    unscii
    vdrsymbols
    vegur
    xits-math
    zilla-slab
  ];
}